services:
  app:
    build:
      context: .
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    links:
      - db
    ports:
      - 50052:50051
  pipeline-server-db:
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db
  mongoexpress:
    image: mongo-express
    ports:
        - "8082:8081"
    links:
      - db
    environment: 
        - ME_CONFIG_MONGODB_URL=mongodb://db:27017
volumes:
  mongodb: