services:
  app:
    build:
      context: .
    volumes:
      - ./:/evalquiz-pipeline-server
    command: python -m evalquiz_pipeline_server.server_component
    ports:
      - 50051:50051
    secrets:
      - openai_api_key
    links:
      - db
  db:
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db
  mongoexpress:
    image: mongo-express
    ports:
        - "8081:8082"
    links:
      - db
    environment: 
        - ME_CONFIG_MONGODB_URL=mongodb://db:27017
volumes:
  mongodb:
secrets:
  openai_api_key:
    file: /tmp/openai_api_key.txt
