services:
  app:
    build:
      context: .
      dockerfile: production-dockerfile
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    image: evalquizcontainers.azurecr.io/evalquiz-pipeline-server
    command: python -m evalquiz_pipeline_server.server_component
    ports:
      - 50051:50051
    links:
      - db
  db:
    image: mongo
    restart: always
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
