name: Build and push to Azure Container Registry - EvalQuizPipelineServer

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://evalquizcontainers.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername }}
          password: ${{ secrets.AzureAppService_ContainerPassword }}
      - run: |
          docker build -f ./production-dockerfile . -t evalquizcontainers.azurecr.io/evalquiz-pipeline-server
          docker push evalquizcontainers.azurecr.io/evalquiz-pipeline-server
