name: Evalquiz check for code typing, linting and formatting

on:
  push:
    branches:
      - master

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            # Linting with pyflakes
            pyflakes .
            # Type checking with mypy
            mypy .
            # Code format checking with black
            black . --check
            Test with pytest
            pytest .
